import mongoose from 'mongoose';
import dotenv from 'dotenv';
import bcrypt from 'bcryptjs';

dotenv.config();

import User from '../models/User.js';
import Category from '../models/Category.js';
import Equipment from '../models/Equipment.js';
import Order from '../models/Order.js';
import Payment from '../models/Payment.js';
import Rental from '../models/Rental.js';
import Delivery from '../models/Delivery.js';
import Review from '../models/Review.js';
import Notification from '../models/Notification.js';

const seedDatabase = async () => {
  try {
    const mongoUri = process.env.MONGO_URI || 'mongodb://127.0.0.1:27017/medrentia';
    await mongoose.connect(mongoUri);
    console.log(`[MedRentia Seed] Connected to MongoDB at ${mongoUri}`);

    // Clear existing collections
    await User.deleteMany();
    await Category.deleteMany();
    await Equipment.deleteMany();
    await Order.deleteMany();
    await Payment.deleteMany();
    await Rental.deleteMany();
    await Delivery.deleteMany();
    await Review.deleteMany();
    await Notification.deleteMany();

    console.log('[MedRentia Seed] Cleared existing data');

    // 1. Create Seed Users
    const hashedPassword = await bcrypt.hash('MedRentia@123', 10);

    const users = await User.insertMany([
      {
        name: 'Rahul Sharma',
        email: 'customer@medrentia.test',
        phone: '+91 98450 12345',
        password: hashedPassword,
        role: 'customer',
        profileImage: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=400&q=80',
        address: {
          street: 'Flat 402, Green Glen Layout, Bellandur',
          city: 'Bengaluru',
          state: 'Karnataka',
          pincode: '560103',
          landmark: 'Opposite Central Mall',
        },
        isVerified: true,
        isActive: true,
      },
      {
        name: 'Apex Healthcare Solutions Pvt Ltd',
        email: 'provider@medrentia.test',
        phone: '+91 98860 67890',
        password: hashedPassword,
        role: 'provider',
        companyName: 'Apex MedEquip Bangalore Hub',
        businessLicense: 'BL-MED-2024-99881',
        profileImage: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&w=400&q=80',
        address: {
          street: '12th Main, HAL 2nd Stage, Indiranagar',
          city: 'Bengaluru',
          state: 'Karnataka',
          pincode: '560038',
          landmark: 'Near Indiranagar Metro',
        },
        isVerified: true,
        isActive: true,
      },
      {
        name: 'MedRentia Super Administrator',
        email: 'admin@medrentia.test',
        phone: '+91 80063 37368',
        password: hashedPassword,
        role: 'admin',
        companyName: 'MedRentia HQ',
        profileImage: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&w=400&q=80',
        address: {
          street: 'MedRentia Tower, MG Road',
          city: 'Bengaluru',
          state: 'Karnataka',
          pincode: '560001',
        },
        isVerified: true,
        isActive: true,
      },
    ]);

    const [customerUser, providerUser, adminUser] = users;
    console.log('[MedRentia Seed] Created Demo Users (Customer, Provider, Admin)');

    // 2. Create Healthcare Categories (9 Categories)
    const categoryData = [
      {
        name: 'Mobility Equipment',
        slug: 'mobility-equipment',
        description: 'Wheelchairs, motorized power chairs, walkers, crutches, and patient transfer hoists.',
        iconName: 'Accessibility',
        image: 'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Home Healthcare Equipment',
        slug: 'home-healthcare-equipment',
        description: 'Adjustable manual & electric hospital beds, anti-bedsore mattresses, commode chairs, and walking sticks.',
        iconName: 'Home',
        image: 'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Respiratory Equipment',
        slug: 'respiratory-equipment',
        description: 'Medical oxygen concentrators, CPAP/BiPAP sleep therapy machines, cylinders, and compressor nebulizers.',
        iconName: 'Wind',
        image: 'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Monitoring Devices',
        slug: 'monitoring-devices',
        description: 'Multi-parameter bedside patient monitors, continuous pulse oximeters, digital BP monitors, and ECG units.',
        iconName: 'Activity',
        image: 'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Diagnostic Equipment',
        slug: 'diagnostic-equipment',
        description: 'Portable color Doppler ultrasound machines, 12-channel ECG electrocardiographs, and mobile X-ray scanners.',
        iconName: 'Stethoscope',
        image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Therapy & Rehabilitation',
        slug: 'therapy-rehabilitation',
        description: 'Active-passive motorized physiotherapy cycles, 4-channel digital TENS pain relievers, and continuous passive motion (CPM) units.',
        iconName: 'Smile',
        image: 'https://images.unsplash.com/photo-1576091160399-112ba8d25d1d?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'ICU Equipment',
        slug: 'icu-equipment',
        description: 'Invasive & Non-invasive ICU ventilators, multi-lead cardiac monitors, automated external defibrillators (AED), and syringe infusion pumps.',
        iconName: 'HeartPulse',
        image: 'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Surgical Equipment',
        slug: 'surgical-equipment',
        description: 'High-vacuum surgical suction units, precision syringe drivers, micro-infusion volumetric pumps, and cautery instruments.',
        iconName: 'Scissors',
        image: 'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=800&q=80',
      },
      {
        name: 'Specialized Equipment',
        slug: 'specialized-equipment',
        description: 'Hemodialysis clinical units, modular wheelchair access ramps, and pediatric oxygen therapy units.',
        iconName: 'ShieldCheck',
        image: 'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
      },
    ];

    const categories = await Category.insertMany(categoryData);
    console.log('[MedRentia Seed] Created 9 Healthcare Categories');

    const catMap = {};
    categories.forEach((cat) => {
      catMap[cat.name] = cat._id;
    });

    // 3. Create Seed Medical Equipment (Strictly mapped exact images and descriptions in ₹ INR)
    const equipmentList = [
      {
        name: 'Ergonomic Folding Wheelchair',
        slug: 'wheelchair-ergonomic-folding',
        category: catMap['Mobility Equipment'],
        categoryName: 'Mobility Equipment',
        shortDescription: 'Lightweight aircraft-grade aluminum wheelchair with padded armrests, swing-away footrests, and puncture-proof mag wheels.',
        description: 'Designed for daily comfort and mobility assistance. Features high-grade breathable nylon upholstery, dual handbrakes for companion safety, and a quick-fold mechanism fitting standard car boots. Cleaned with hospital-grade sanitization protocols.',
        images: [
          'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
          'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80',
        ],
        dailyPrice: 150,
        weeklyPrice: 750,
        monthlyPrice: 2200,
        sixMonthPrice: 11000,
        yearlyPrice: 19500,
        securityDeposit: 1500,
        deliveryFee: 120,
        quantity: 12,
        availableQuantity: 10,
        rentedQuantity: 2,
        condition: 'Brand New',
        availability: 'Available',
        hygieneStatus: 'Certified Sanitized & Sealed',
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560038', area: 'Indiranagar' },
        provider: providerUser._id,
        providerName: 'Apex MedEquip Bangalore Hub',
        features: ['Foldable lightweight frame (11.5 kg)', 'Weight capacity up to 125 kg', 'Puncture-resistant polyurethane tires', 'Anti-tipping rear support wheels'],
        specifications: {
          Weight: '11.5 kg',
          'Weight Capacity': '125 kg',
          'Seat Width': '18 inches',
          Brakes: 'Dual Companion & Wheel Locks',
        },
        rating: 4.9,
        reviewCount: 38,
        totalRentals: 45,
        totalRevenue: 68000,
        isFeatured: true,
      },
      {
        name: 'Motorized Electric Power Wheelchair',
        slug: 'electric-wheelchair-power',
        category: catMap['Mobility Equipment'],
        categoryName: 'Mobility Equipment',
        shortDescription: '360° joystick-controlled motorized electric wheelchair with dual 250W brushless motors and 20 km lithium battery range.',
        description: 'Ultimate personal independence for elderly and post-op recovery patients. Features smooth electromagnetic regenerative brakes, intelligent micro-controller joystick that can be fitted to either left or right armrest, and cushioned orthopedic seat.',
        images: [
          'https://images.unsplash.com/photo-1576091160550-2173dba999ef?auto=format&fit=crop&w=800&q=80',
        ],
        dailyPrice: 450,
        weeklyPrice: 2400,
        monthlyPrice: 7500,
        sixMonthPrice: 38000,
        yearlyPrice: 68000,
        securityDeposit: 5000,
        deliveryFee: 200,
        quantity: 6,
        availableQuantity: 4,
        rentedQuantity: 2,
        condition: 'Excellent',
        availability: 'Available',
        hygieneStatus: 'Certified Sanitized & Sealed',
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560038', area: 'HAL Stage 2' },
        provider: providerUser._id,
        providerName: 'Apex MedEquip Bangalore Hub',
        features: ['20 km range on single charge', 'Smart 360-degree joystick control', 'Electromagnetic automatic braking', 'Quick folding for SUV transport'],
        specifications: {
          Motors: 'Dual 250W Brushless',
          Battery: '24V 12Ah Lithium-ion',
          'Max Speed': '6 km/h',
          'Weight Capacity': '135 kg',
        },
        rating: 4.8,
        reviewCount: 19,
        totalRentals: 26,
        totalRevenue: 145000,
        isFeatured: true,
      },
      {
        name: 'Manual 2-Function Hospital Bed',
        slug: 'hospital-bed-manual-2-function',
        category: catMap['Home Healthcare Equipment'],
        categoryName: 'Home Healthcare Equipment',
        shortDescription: 'Dual crank manual hospital bed with adjustable backrest (0-75°) and knee elevation (0-45°), collapsible aluminum side railings.',
        description: 'Hospital grade patient care bed for home convalescence. Powder-coated mild steel frame, 5-inch noiseless medical castor wheels with diagonal braking, and integrated IV pole socket.',
        images: [
          'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
        ],
        dailyPrice: 250,
        weeklyPrice: 1400,
        monthlyPrice: 4200,
        sixMonthPrice: 21000,
        yearlyPrice: 38000,
        securityDeposit: 3000,
        deliveryFee: 300,
        quantity: 8,
        availableQuantity: 5,
        rentedQuantity: 3,
        condition: 'Excellent',
        availability: 'Available',
        hygieneStatus: 'Certified Sanitized & Sealed',
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560001', area: 'CBD' },
        provider: providerUser._id,
        providerName: 'Apex MedEquip Bangalore Hub',
        features: ['Smooth twin manual cranks', 'Collapsible safety side rails', 'Noiseless lockable castors', 'Includes waterproof 4-inch medical mattress'],
        specifications: {
          'Backrest Angle': '0 to 75 degrees',
          'Knee Rest Angle': '0 to 45 degrees',
          Dimensions: '2100 x 960 x 500 mm',
          Frame: 'Powder-coated Mild Steel',
        },
        rating: 4.9,
        reviewCount: 42,
        totalRentals: 58,
        totalRevenue: 180000,
        isFeatured: true,
      },
      {
        name: 'Full Electric 5-Function ICU Bed',
        slug: 'icu-bed-electric-5-function',
        category: catMap['ICU Equipment'],
        categoryName: 'ICU Equipment',
        shortDescription: 'Linak electric motor ICU bed with remote control backrest, leg elevation, height adjust, Trendelenburg & reverse Trendelenburg.',
        description: 'Critical care motorized bed with CPR quick-release lever, nurse control panel at footboard, integrated digital angle indicator, and built-in battery backup for uninterrupted power.',
        images: [
          'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
        ],
        dailyPrice: 750,
        weeklyPrice: 4500,
        monthlyPrice: 14000,
        sixMonthPrice: 72000,
        yearlyPrice: 130000,
        securityDeposit: 10000,
        deliveryFee: 500,
        quantity: 5,
        availableQuantity: 3,
        rentedQuantity: 2,
        condition: 'Brand New',
        availability: 'Available',
        hygieneStatus: 'Certified Sanitized & Sealed',
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560038', area: 'Indiranagar' },
        provider: providerUser._id,
        providerName: 'Apex MedEquip Bangalore Hub',
        features: ['5-Position motorized adjustment', 'Linak Denmark actuator motors', 'CPR emergency flatten lever', 'Trendelenburg ±12 degrees'],
        specifications: {
          'Motor System': '4 Linak Actuators',
          'Max Patient Weight': '220 kg',
          Functions: 'Back, Leg, Hi-Lo, Trendelenburg, Rev-Trendelenburg',
          'Battery Backup': 'Up to 24 hours on standby',
        },
        rating: 5.0,
        reviewCount: 27,
        totalRentals: 31,
        totalRevenue: 340000,
        isFeatured: true,
      },
      {
        name: 'Philips Respironics 5L Oxygen Concentrator',
        slug: 'oxygen-concentrator-5l-philips',
        category: catMap['Respiratory Equipment'],
        categoryName: 'Respiratory Equipment',
        shortDescription: 'Continuous medical oxygen concentrator delivering 0.5 to 5.0 LPM at 93% ± 3% purity with built-in OPI purity sensor.',
        description: 'Compact, ultra-quiet (45 dBA) and energy-efficient oxygen machine. Includes humidifier bottle, adult nasal cannulas, and comprehensive OPI oxygen percentage indicator for maximum patient safety.',
        images: [
          'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=800&q=80',
        ],
        dailyPrice: 300,
        weeklyPrice: 1750,
        monthlyPrice: 5500,
        sixMonthPrice: 28000,
        yearlyPrice: 49000,
        securityDeposit: 4000,
        deliveryFee: 150,
        quantity: 10,
        availableQuantity: 7,
        rentedQuantity: 3,
        condition: 'Excellent',
        availability: 'Available',
        hygieneStatus: 'Certified Sanitized & Sealed',
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560038', area: 'Indiranagar' },
        provider: providerUser._id,
        providerName: 'Apex MedEquip Bangalore Hub',
        features: ['93% ± 3% Oxygen purity output', 'Continuous flow 0.5 – 5 LPM', 'Ultra-quiet 45 dBA sound level', 'Integrated digital purity sensor'],
        specifications: {
          'Flow Rate': '0.5 – 5.0 LPM',
          Purity: '93% ± 3%',
          'Sound Level': '45 dBA',
          Power: '350 Watts',
        },
        rating: 4.9,
        reviewCount: 64,
        totalRentals: 82,
        totalRevenue: 395000,
        isFeatured: true,
      },
      {
        name: 'Compressor Medical Nebulizer Kit',
        slug: 'nebulizer-compressor-kit',
        category: catMap['Respiratory Equipment'],
        categoryName: 'Respiratory Equipment',
        shortDescription: 'High-efficiency aerosol compressor nebulizer for asthma, bronchitis, and respiratory medication therapy with adult & child masks.',
        description: 'Produces fine medication aerosol droplets (MMAD ≤ 3.0 µm) ensuring deep pulmonary drug deposition. Oil-free piston pump with low noise output and complete sterile accessories kit.',
        images: [
          'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?auto=format&fit=crop&w=800&q=80',
        ],
        dailyPrice: 80,
        weeklyPrice: 350,
        monthlyPrice: 950,
        sixMonthPrice: 4500,
        yearlyPrice: 8000,
        securityDeposit: 500,
        deliveryFee: 99,
        quantity: 15,
        availableQuantity: 12,
        rentedQuantity: 3,
        condition: 'Brand New',
        availability: 'Available',
        hygieneStatus: 'Certified Sanitized & Sealed',
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560038', area: 'Indiranagar' },
        provider: providerUser._id,
        providerName: 'Apex MedEquip Bangalore Hub',
        features: ['Particle size MMAD ≤ 3.0 µm', 'High nebulization rate 0.35 ml/min', 'Includes Adult & Child masks', 'Thermal protector overheat safety'],
        specifications: {
          'Flow Rate': '6-8 LPM',
          'Particle Size': '< 3.0 microns',
          Weight: '1.4 kg',
          'Sound Level': '< 58 dBA',
        },
        rating: 4.8,
        reviewCount: 22,
        totalRentals: 36,
        totalRevenue: 28500,
        isFeatured: true,
      },
      {
        name: 'ResMed Auto-CPAP Sleep Therapy System',
        slug: 'cpap-machine-resmed-auto',
        category: catMap['Respiratory Equipment'],
        categoryName: 'Respiratory Equipment',
        shortDescription: 'AutoSet CPAP sleep apnea device with integrated heated humidifier, climate line tubing, and nasal mask for sleep therapy.',
        description: 'Auto-adjusting positive airway pressure algorithm that dynamically modulates pressure based on flow limitation, snoring, and apnea events. Features EPR pressure relief for smooth natural breathing and cellular sleep report tracking.',
        images: [
          'https://images.unsplash.com/photo-1588776814546-1ffcf47267a5?auto=format&fit=crop&w=800&q=80',
        ],
        dailyPrice: 280,
        weeklyPrice: 1600,
        monthlyPrice: 5000,
        sixMonthPrice: 26000,
        yearlyPrice: 46000,
        securityDeposit: 5000,
        deliveryFee: 150,
        quantity: 7,
        availableQuantity: 4,
        rentedQuantity: 3,
        condition: 'Certified Refurbished',
        availability: 'Available',
        hygieneStatus: 'Certified Sanitized & Sealed',
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560038', area: 'HAL Stage 2' },
        provider: providerUser._id,
        providerName: 'Apex MedEquip Bangalore Hub',
        features: ['AutoSet self-titrating pressure technology', 'Heated HumidAir humidifier chamber', 'EPR Expiratory Pressure Relief', 'SD Card & Cloud Sleep Reporting'],
        specifications: {
          'Pressure Range': '4 to 20 cm H2O',
          'Sound Level': '26.6 dBA Whisper-quiet',
          'Data Tracking': 'AHI, Leak rate, Compliance',
          Weight: '1.24 kg',
        },
        rating: 4.9,
        reviewCount: 31,
        totalRentals: 44,
        totalRevenue: 195000,
        isFeatured: true,
      },
      {
        name: 'Digital Fingertip Pulse Oximeter & Monitor',
        slug: 'pulse-oximeter-digital-fingertip',
        category: catMap['Monitoring Devices'],
        categoryName: 'Monitoring Devices',
        shortDescription: 'OLED multi-directional display pulse oximeter measuring SpO2 oxygen saturation, pulse rate, and perfusion index (PI%).',
        description: 'High-precision optical sensor with ±2% accuracy for blood oxygen saturation. Features real-time plethysmogram graph, auto power-off within 8 seconds, and visual alarm for low oxygen readings.',
        images: [
          'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
        ],
        dailyPrice: 50,
        weeklyPrice: 200,
        monthlyPrice: 600,
        sixMonthPrice: 2800,
        yearlyPrice: 4800,
        securityDeposit: 500,
        deliveryFee: 50,
        quantity: 25,
        availableQuantity: 21,
        rentedQuantity: 4,
        condition: 'Brand New',
        availability: 'Available',
        hygieneStatus: 'Certified Sanitized & Sealed',
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560001', area: 'MG Road' },
        provider: providerUser._id,
        providerName: 'Apex MedEquip Bangalore Hub',
        features: ['Dual-color 4-direction OLED display', 'SpO2 range 70% – 100% (±2%)', 'Perfusion Index (PI) indicator', 'Low battery and audio alarm alerts'],
        specifications: {
          'SpO2 Accuracy': '±2% in 70-100% range',
          'Pulse Range': '30 – 250 bpm',
          Display: 'High Contrast Dual Color OLED',
          Power: '2x AAA Alkaline Batteries',
        },
        rating: 4.8,
        reviewCount: 15,
        totalRentals: 28,
        totalRevenue: 14200,
        isFeatured: false,
      },
      {
        name: 'Foldable Lightweight Aluminum Walker',
        slug: 'walker-foldable-aluminum',
        category: catMap['Mobility Equipment'],
        categoryName: 'Mobility Equipment',
        shortDescription: 'Height-adjustable reciprocal walking frame with dual front wheels and non-slip contoured handgrips.',
        description: 'Sturdy 1-inch anodized aluminum tubing offering maximum stability for rehabilitation and geriatric mobility. Features a single-button quick fold mechanism and durable rubber ferrule tip rear glides.',
        images: [
          'https://images.unsplash.com/photo-1584515933487-779824d29309?auto=format&fit=crop&w=800&q=80',
        ],
        dailyPrice: 60,
        weeklyPrice: 280,
        monthlyPrice: 850,
        sixMonthPrice: 4200,
        yearlyPrice: 7200,
        securityDeposit: 800,
        deliveryFee: 99,
        quantity: 18,
        availableQuantity: 14,
        rentedQuantity: 4,
        condition: 'Brand New',
        availability: 'Available',
        hygieneStatus: 'Certified Sanitized & Sealed',
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560038', area: 'Indiranagar' },
        provider: providerUser._id,
        providerName: 'Apex MedEquip Bangalore Hub',
        features: ['Reciprocal walking action mode', '8-Level push button height adjust', 'Dual 5-inch front steering wheels', 'Total weight only 2.4 kg'],
        specifications: {
          'Height Adjustment': '76 cm to 94 cm',
          Weight: '2.4 kg',
          'Weight Capacity': '115 kg',
          Material: 'Anodized Aluminum Alloy',
        },
        rating: 4.7,
        reviewCount: 29,
        totalRentals: 41,
        totalRevenue: 31000,
        isFeatured: false,
      },
      {
        name: 'Adjustable Underarm Aluminum Crutches (Pair)',
        slug: 'crutches-adjustable-underarm-pair',
        category: catMap['Mobility Equipment'],
        categoryName: 'Mobility Equipment',
        shortDescription: 'Orthopedic underarm walking crutches with soft silicone pads and push-pin dual height/arm adjustments.',
        description: 'Ideal for post-fracture and lower extremity rehabilitation. Engineered with reinforced extruded aluminum tubing and heavy-duty shock-absorbing non-skid rubber base ferrules.',
        images: [
          'https://images.unsplash.com/photo-1582719478250-c89cae4dc85b?auto=format&fit=crop&w=800&q=80',
        ],
        dailyPrice: 40,
        weeklyPrice: 180,
        monthlyPrice: 550,
        sixMonthPrice: 2600,
        yearlyPrice: 4500,
        securityDeposit: 500,
        deliveryFee: 80,
        quantity: 20,
        availableQuantity: 16,
        rentedQuantity: 4,
        condition: 'Brand New',
        availability: 'Available',
        hygieneStatus: 'Certified Sanitized & Sealed',
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560038', area: 'Indiranagar' },
        provider: providerUser._id,
        providerName: 'Apex MedEquip Bangalore Hub',
        features: ['Dual push-button height regulation', 'Cushioned hypo-allergenic underarm pads', 'Shock-absorbing anti-slip rubber bases', 'Available in Medium & Large sizes'],
        specifications: {
          'Height Range': '114 cm to 134 cm (Medium)',
          'Weight Capacity': '130 kg',
          Material: 'High-strength Aluminum Extrusion',
        },
        rating: 4.8,
        reviewCount: 18,
        totalRentals: 30,
        totalRevenue: 15400,
        isFeatured: false,
      },
      {
        name: 'Multi-Parameter Bedside Patient Monitor',
        slug: 'patient-monitor-multipara-bedside',
        category: catMap['Monitoring Devices'],
        categoryName: 'Monitoring Devices',
        shortDescription: '12.1-inch color TFT patient monitor with 5-lead ECG, NIBP, SpO2, Respiration, Dual Temperature, and Pulse Rate.',
        description: 'Hospital grade continuous vital signs monitor with 72-hour trend review, audio-visual alarm limit configuration, built-in rechargeable battery, and thermal printer recorder interface.',
        images: [
          'https://images.unsplash.com/photo-1530497610245-94d3c16cda28?auto=format&fit=crop&w=800&q=80',
        ],
        dailyPrice: 400,
        weeklyPrice: 2200,
        monthlyPrice: 6800,
        sixMonthPrice: 35000,
        yearlyPrice: 62000,
        securityDeposit: 6000,
        deliveryFee: 200,
        quantity: 6,
        availableQuantity: 4,
        rentedQuantity: 2,
        condition: 'Excellent',
        availability: 'Available',
        hygieneStatus: 'Certified Sanitized & Sealed',
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560038', area: 'Indiranagar' },
        provider: providerUser._id,
        providerName: 'Apex MedEquip Bangalore Hub',
        features: ['12.1-inch High resolution color TFT display', '5-Lead ECG waveform & ST analysis', 'Adult & Pediatric NIBP cuffs included', 'Rechargeable Li-ion battery backup'],
        specifications: {
          Parameters: 'ECG, NIBP, SpO2, Resp, Temp, PR',
          'Display Size': '12.1 inch TFT',
          Memory: '72-Hour graphic & tabular trends',
          Safety: 'Defibrillator & Electrosurgical protection',
        },
        rating: 4.9,
        reviewCount: 24,
        totalRentals: 35,
        totalRevenue: 215000,
        isFeatured: true,
      },
      {
        name: 'Portable ICU Medical Ventilator',
        slug: 'ventilator-portable-icu-medical',
        category: catMap['ICU Equipment'],
        categoryName: 'ICU Equipment',
        shortDescription: 'Turbine-driven invasive and non-invasive transport ICU ventilator with touchscreen controls and comprehensive lung mechanics monitoring.',
        description: 'Advanced critical care ventilator for adult and pediatric respiratory failure. Supports VCV, PCV, SIMV, PSV, and CPAP/BiPAP modes. Features internal high-efficiency turbine eliminating external compressed air requirements, paired with 4-hour hot-swappable batteries.',
        images: [
          'https://images.unsplash.com/photo-1516549655169-df83a0774514?auto=format&fit=crop&w=800&q=80',
        ],
        dailyPrice: 1500,
        weeklyPrice: 9000,
        monthlyPrice: 28000,
        sixMonthPrice: 145000,
        yearlyPrice: 260000,
        securityDeposit: 20000,
        deliveryFee: 500,
        quantity: 4,
        availableQuantity: 2,
        rentedQuantity: 2,
        condition: 'Brand New',
        availability: 'Available',
        hygieneStatus: 'Certified Sanitized & Sealed',
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560038', area: 'HAL Stage 2' },
        provider: providerUser._id,
        providerName: 'Apex MedEquip Bangalore Hub',
        features: ['Invasive & Non-invasive support modes', 'Built-in high performance turbine compressor', '10.4-inch color touch control interface', '4-Hour internal battery operation'],
        specifications: {
          'Ventilation Modes': 'VCV, PCV, SIMV-V, SIMV-P, PSV, CPAP',
          'Tidal Volume': '20 – 2000 ml',
          'FiO2 Range': '21% to 100%',
          'Peak Flow': 'Up to 210 LPM',
        },
        rating: 5.0,
        reviewCount: 16,
        totalRentals: 21,
        totalRevenue: 490000,
        isFeatured: true,
      },
      {
        name: 'Anti-Bedsore Alternating Pressure Air Mattress',
        slug: 'hospital-mattress-anti-bedsore-air',
        category: catMap['Home Healthcare Equipment'],
        categoryName: 'Home Healthcare Equipment',
        shortDescription: 'Medical grade 130 bubble-cell alternating air mattress with ultra-silent pressure adjustment compressor pump.',
        description: 'Clinically proven prevention and treatment for stage 1 & 2 pressure ulcers/bedsores. Features 6-minute alternating inflation and deflation cycles to distribute body weight and improve capillary blood circulation.',
        images: [
          'https://images.unsplash.com/photo-1519494026892-80bbd2d6fd0d?auto=format&fit=crop&w=800&q=80',
        ],
        dailyPrice: 100,
        weeklyPrice: 480,
        monthlyPrice: 1500,
        sixMonthPrice: 7500,
        yearlyPrice: 13500,
        securityDeposit: 1000,
        deliveryFee: 120,
        quantity: 14,
        availableQuantity: 10,
        rentedQuantity: 4,
        condition: 'Brand New',
        availability: 'Available',
        hygieneStatus: 'Certified Sanitized & Sealed',
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560038', area: 'Indiranagar' },
        provider: providerUser._id,
        providerName: 'Apex MedEquip Bangalore Hub',
        features: ['130 Bubble cells alternating pressure system', 'Ultra-quiet (< 20 dB) micro-pump', 'Medical PVC waterproof & antibacterial material', 'Includes patch repair kit and hanging brackets'],
        specifications: {
          'Cycle Time': '6 Minutes',
          'Pressure Range': '40 – 100 mmHg',
          Dimensions: '200 x 90 x 7 cm',
          'Weight Capacity': '135 kg',
        },
        rating: 4.8,
        reviewCount: 35,
        totalRentals: 49,
        totalRevenue: 62000,
        isFeatured: false,
      },
      {
        name: 'Foldable Bedside Commode Chair',
        slug: 'commode-chair-foldable-bedside',
        category: catMap['Home Healthcare Equipment'],
        categoryName: 'Home Healthcare Equipment',
        shortDescription: 'Stainless steel rust-free bedside commode chair with removable pan, lid, and height-adjustable legs.',
        description: 'Dignified, comfortable hygiene aid for post-surgery and elderly patients. Features soft armrests, spill-proof splash guard, and easy-clean removable waste bucket.',
        images: [
          'https://images.unsplash.com/photo-1584515979956-d9f6e5d09982?auto=format&fit=crop&w=800&q=80',
        ],
        dailyPrice: 70,
        weeklyPrice: 320,
        monthlyPrice: 950,
        sixMonthPrice: 4800,
        yearlyPrice: 8500,
        securityDeposit: 800,
        deliveryFee: 100,
        quantity: 12,
        availableQuantity: 9,
        rentedQuantity: 3,
        condition: 'Brand New',
        availability: 'Available',
        hygieneStatus: 'Certified Sanitized & Sealed',
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560038', area: 'Indiranagar' },
        provider: providerUser._id,
        providerName: 'Apex MedEquip Bangalore Hub',
        features: ['Foldable frame for compact storage', '5-Level push button height regulation', 'Includes bucket with lid & splash shield', 'Non-slip suction rubber feet'],
        specifications: {
          Frame: 'Chrome-plated Stainless Steel',
          'Weight Capacity': '120 kg',
          'Bucket Capacity': '6 Liters',
        },
        rating: 4.7,
        reviewCount: 20,
        totalRentals: 27,
        totalRevenue: 21000,
        isFeatured: false,
      },
      {
        name: 'Volumetric Micro-Infusion Syringe Pump',
        slug: 'syringe-pump-precision-micro',
        category: catMap['Surgical Equipment'],
        categoryName: 'Surgical Equipment',
        shortDescription: 'High precision programmable syringe pump compatible with 5ml to 60ml syringes with anti-bolus occlusion detection.',
        description: 'Designed for accurate continuous intravenous delivery of critical ICU medications, analgesics, and chemotherapy. Visual LED display with rate calibration from 0.1 to 1500 ml/h.',
        images: [
          'https://images.unsplash.com/photo-1551076805-e1869033e561?auto=format&fit=crop&w=800&q=80',
        ],
        dailyPrice: 220,
        weeklyPrice: 1200,
        monthlyPrice: 3800,
        sixMonthPrice: 19500,
        yearlyPrice: 35000,
        securityDeposit: 3500,
        deliveryFee: 120,
        quantity: 8,
        availableQuantity: 6,
        rentedQuantity: 2,
        condition: 'Certified Refurbished',
        availability: 'Available',
        hygieneStatus: 'Certified Sanitized & Sealed',
        location: { city: 'Bengaluru', state: 'Karnataka', pincode: '560038', area: 'Indiranagar' },
        provider: providerUser._id,
        providerName: 'Apex MedEquip Bangalore Hub',
        features: ['Universal syringe compatibility 5ml - 60ml', 'Accuracy ±2% with digital calibration', 'Dynamic pressure occlusion monitoring', '6-Hour rechargeable battery'],
        specifications: {
          'Flow Rate Range': '0.1 – 1500 ml/h',
          'Bolus Rate': 'Up to 1500 ml/h',
          Alarms: 'Occlusion, Near Empty, Disengaged, Low Battery',
        },
        rating: 4.9,
        reviewCount: 14,
        totalRentals: 19,
        totalRevenue: 64000,
        isFeatured: false,
      },
    ];

    const equipmentDocs = await Equipment.insertMany(equipmentList);
    console.log(`[MedRentia Seed] Inserted ${equipmentDocs.length} Verified Medical Devices`);

    // 4. Create Sample Orders, Payments, Rentals, Deliveries, and Reviews
    const sampleEquipment = equipmentDocs[0]; // Wheelchair
    const orderStartDate = new Date(Date.now() - 3 * 24 * 60 * 60 * 1000);
    const orderEndDate = new Date(Date.now() + 11 * 24 * 60 * 60 * 1000);

    const sampleOrder = await Order.create({
      orderId: 'MED-784920',
      customer: customerUser._id,
      customerName: customerUser.name,
      customerEmail: customerUser.email,
      customerPhone: customerUser.phone,
      items: [
        {
          equipment: sampleEquipment._id,
          name: sampleEquipment.name,
          image: sampleEquipment.images[0],
          categoryName: sampleEquipment.categoryName,
          rentalDuration: 'weekly',
          durationUnits: 2,
          rentalPrice: 1500,
          securityDeposit: 1500,
          quantity: 1,
          rentalStartDate: orderStartDate,
          rentalEndDate: orderEndDate,
          provider: providerUser._id,
          providerName: providerUser.companyName,
        },
      ],
      deliveryAddress: {
        street: 'Flat 402, Green Glen Layout, Bellandur',
        city: 'Bengaluru',
        state: 'Karnataka',
        pincode: '560103',
        contactPhone: '+91 98450 12345',
        landmark: 'Near Central Mall',
      },
      rentalFee: 1500,
      totalDeposit: 1500,
      deliveryFee: 120,
      tax: 270,
      totalAmount: 3390,
      paymentStatus: 'paid',
      orderStatus: 'Active Rental',
      razorpayOrderId: 'order_med_sample9988',
      razorpayPaymentId: 'pay_med_sample4432',
    });

    const samplePayment = await Payment.create({
      order: sampleOrder._id,
      orderId: sampleOrder.orderId,
      customer: customerUser._id,
      razorpayOrderId: sampleOrder.razorpayOrderId,
      razorpayPaymentId: sampleOrder.razorpayPaymentId,
      amount: sampleOrder.totalAmount,
      currency: 'INR',
      paymentMethod: 'UPI',
      status: 'captured',
      receiptNumber: `REC-${sampleOrder.orderId}`,
    });

    sampleOrder.paymentId = samplePayment._id;
    await sampleOrder.save();

    const sampleRental = await Rental.create({
      order: sampleOrder._id,
      orderId: sampleOrder.orderId,
      customer: customerUser._id,
      provider: providerUser._id,
      equipment: sampleEquipment._id,
      equipmentName: sampleEquipment.name,
      equipmentImage: sampleEquipment.images[0],
      categoryName: sampleEquipment.categoryName,
      rentalDuration: 'weekly',
      startDate: orderStartDate,
      endDate: orderEndDate,
      originalEndDate: orderEndDate,
      rentalFee: 1500,
      depositAmount: 1500,
      status: 'Active',
      isReviewed: true,
    });

    await Delivery.create({
      order: sampleOrder._id,
      orderId: sampleOrder.orderId,
      customer: customerUser._id,
      provider: providerUser._id,
      currentStatus: 'Delivered',
      deliveryAgentName: 'Vikram Singh (Express Logistics)',
      deliveryAgentPhone: '+91 99887 76655',
      trackingCode: 'TRK-MED-849201',
      estimatedDeliveryTime: orderStartDate,
      actualDeliveryTime: orderStartDate,
      deliveryAddress: sampleOrder.deliveryAddress,
      timeline: [
        {
          status: 'Order Confirmed',
          description: 'Payment verified and rental order placed.',
          completed: true,
          timestamp: orderStartDate,
        },
        {
          status: 'Preparing Equipment',
          description: 'Provider retrieved equipment from sanitized storage.',
          completed: true,
          timestamp: orderStartDate,
        },
        {
          status: 'Sanitization & Quality Check',
          description: 'Hospital-grade autoclaving & mechanical brake checks certified.',
          completed: true,
          timestamp: orderStartDate,
        },
        {
          status: 'Packed',
          description: 'Sealed in hygienic protective medical film.',
          completed: true,
          timestamp: orderStartDate,
        },
        {
          status: 'Out for Delivery',
          description: 'Dispatched with MedRentia Express Logistics.',
          completed: true,
          timestamp: orderStartDate,
        },
        {
          status: 'Delivered',
          description: 'Equipment safely handed over at doorstep and demonstration provided.',
          completed: true,
          timestamp: orderStartDate,
        },
        {
          status: 'Returned',
          description: 'Pending rental completion.',
          completed: false,
        },
      ],
    });

    // Sample Verified Review
    await Review.create({
      equipment: sampleEquipment._id,
      rental: sampleRental._id,
      customer: customerUser._id,
      customerName: customerUser.name,
      provider: providerUser._id,
      rating: 5,
      title: 'Spotless clean wheelchair, delivered within 3 hours!',
      comment: 'We needed a wheelchair urgently for my mother after knee replacement surgery. The MedRentia team sanitized it thoroughly and the delivery boy showed us how to fold and lock the brakes easily. Highly recommended service!',
      hygieneRating: 5,
      deliveryRating: 5,
      verifiedRental: true,
    });

    // Notifications
    await Notification.create({
      recipient: customerUser._id,
      title: 'Active Rental Reminder',
      message: `Your rental for "${sampleEquipment.name}" is currently active until ${orderEndDate.toLocaleDateString('en-IN')}. You can extend or request return anytime from your dashboard.`,
      type: 'Rental Starting',
      orderId: sampleOrder.orderId,
      equipmentId: sampleEquipment._id,
    });

    console.log('[MedRentia Seed] Successfully populated complete database!');
    process.exit(0);
  } catch (error) {
    console.error('[MedRentia Seed Error]:', error);
    process.exit(1);
  }
};

seedDatabase();
